import React, { useState, useRef, useEffect } from 'react';
import { GeneratedCopy, GeneratedImage, ProductInfo, QualityReport } from '../types';
import CoverComposer, { TEXT_STYLES, TextStyle } from './CoverComposer';
import { generatePosterCopy } from '../services/api';
// @ts-ignore
import html2canvas from 'html2canvas';

interface Props {
  copy: GeneratedCopy;
  image: GeneratedImage;
  productInfo: ProductInfo;
  llmApiKey: string;
  onReset: () => void;
  onRegenerateImage: () => void;
}

const QualityCheckCard: React.FC<{ report: QualityReport }> = ({ report }) => {
  if (!report) return null;

  return (
    <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm mb-6 animate-fade-in-up">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-black text-gray-800 flex items-center gap-2 uppercase tracking-widest">
          <i className="fas fa-clipboard-check text-xhs-red"></i> 
          封面美学 QC
        </h3>
        <span className="text-[10px] bg-green-50 text-green-600 px-2 py-0.5 rounded-full font-bold">形态验证通过</span>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {[
          { label: '商业设计感', data: report?.subject, icon: 'fa-eye' },
          { label: '场景带入感', data: report?.function, icon: 'fa-couch' },
          { label: '光影高级感', data: report?.structure, icon: 'fa-sun' },
          { label: '构图平衡度', data: report?.concept, icon: 'fa-border-all' }
        ].map((item, idx) => (
          <div key={idx} className="flex flex-col gap-1.5 p-3 rounded-2xl bg-gray-50/50 border border-gray-100">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold text-gray-500 flex items-center gap-2">
                <i className={`fas ${item.icon} text-[10px]`}></i> {item.label}
              </span>
              <span className="text-xs font-black text-xhs-red">{item.data?.score || '-'}<span className="text-[10px] text-gray-400 font-normal">/10</span></span>
            </div>
            <p className="text-[11px] text-gray-400 leading-snug">{item.data?.reason || "暂无详细分析数据"}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

const ResultPreview: React.FC<Props> = ({ copy, image, productInfo, llmApiKey, onReset, onRegenerateImage }) => {
  // Local state for edits
  const [editableCopy, setEditableCopy] = useState(copy);
  const [coverText, setCoverText] = useState(copy.title); 
  const [coverStyle, setCoverStyle] = useState<TextStyle>(TEXT_STYLES[0]);
  const [textWidth, setTextWidth] = useState(80); 
  const [fontSize, setFontSize] = useState(26);
  const [aspectRatio, setAspectRatio] = useState<'3:4' | '1:1'>('3:4');
  const [activeTab, setActiveTab] = useState<'content' | 'cover'>('content');
  const [isExporting, setIsExporting] = useState(false);
  const [isResettingText, setIsResettingText] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [showPublishToast, setShowPublishToast] = useState(false);
  const [showCopiedToast, setShowCopiedToast] = useState(false);
  
  const coverRef = useRef<HTMLDivElement>(null);

  // CRITICAL: Update local state when incoming props change (e.g. after regeneration)
  useEffect(() => {
    setEditableCopy(copy);
    setCoverText(copy.title);
  }, [copy]);

  const copyToClipboard = () => {
    const fullText = `标题：${editableCopy.title}\n\n正文：\n${editableCopy.content}\n\n标签：${editableCopy.tags.join(' ')}`;
    navigator.clipboard.writeText(fullText);
    setShowCopiedToast(true);
    setTimeout(() => setShowCopiedToast(false), 2000);
  };

  const handleExportMarkdown = () => {
    const mdContent = `# ${editableCopy.title}\n\n![封面图](${image.url})\n\n## 笔记正文\n${editableCopy.content}\n\n## 标签\n${editableCopy.tags.join(' ')}\n\n---\n*Generated by RedNote Agent*`;
    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${productInfo.name}_小红书策划案.md`;
    a.click();
    URL.revokeObjectURL(url);
    setShowExportMenu(false);
  };

  const handleDownloadImage = async () => {
    if (!coverRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(coverRef.current, { 
        useCORS: true,
        scale: 2,
        logging: false
      });
      const dataUrl = canvas.toDataURL('image/jpeg', 0.9);
      const link = document.createElement('a');
      link.download = `${productInfo.name}_封面.jpg`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      alert('图片下载失败，请重试');
    } finally {
      setIsExporting(false);
    }
  };

  const handlePublish = () => {
    setShowPublishToast(true);
    setTimeout(() => setShowPublishToast(false), 3000);
  };

  const resetCoverTextWithAI = async () => {
    setIsResettingText(true);
    try {
      // Call AI to generate a new attractive slogan
      const newSlogan = await generatePosterCopy(llmApiKey, productInfo);
      // Update only the cover text state
      setCoverText(newSlogan);
    } catch (err) {
      // Fallback: reset to current content title if AI fails
      setCoverText(editableCopy.title);
    } finally {
      setIsResettingText(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto w-full animate-fade-in-up px-2 md:px-0">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <button onClick={onReset} className="text-gray-500 hover:text-gray-800 font-medium flex items-center gap-2">
          <i className="fas fa-chevron-left"></i> 返回修改
        </button>
        
        <div className="flex flex-wrap gap-3 relative w-full md:w-auto">
          <div className="relative">
            <button 
              onClick={copyToClipboard} 
              className="bg-white border border-gray-200 text-gray-700 px-5 py-2 rounded-full font-bold hover:bg-gray-50 transition-colors flex items-center gap-2"
            >
              <i className="far fa-copy"></i>
              复制文案
            </button>
            {showCopiedToast && (
              <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 bg-gray-800 text-white text-[10px] px-3 py-1 rounded-lg shadow-xl animate-fade-in whitespace-nowrap z-50">
                已复制到剪贴板
              </div>
            )}
          </div>
          
          <button 
            onClick={handleDownloadImage}
            disabled={isExporting}
            className="bg-white border border-gray-200 text-gray-700 px-5 py-2 rounded-full font-bold hover:bg-gray-50 transition-colors flex items-center gap-2"
          >
            <i className="far fa-image"></i>
            {isExporting ? '生成中...' : '下载封面图 (JPG)'}
          </button>

          <div className="relative">
            <button 
              onClick={() => setShowExportMenu(!showExportMenu)} 
              className="bg-white border border-xhs-red text-xhs-red px-6 py-2 rounded-full font-bold hover:bg-red-50 transition-all flex items-center gap-2"
            >
              <i className="fas fa-file-export"></i>
              下载策划案
            </button>
            {showExportMenu && (
              <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-xl shadow-xl border border-gray-100 z-50 overflow-hidden animate-fade-in">
                <button onClick={handleExportMarkdown} className="w-full text-left px-4 py-3 hover:bg-gray-50 flex items-center gap-3 text-sm font-bold text-gray-700">
                  <i className="fab fa-markdown text-blue-500"></i> 下载 Markdown (.md)
                </button>
              </div>
            )}
          </div>

          <button 
            onClick={handlePublish}
            className="bg-xhs-red text-white px-6 py-2 rounded-full font-bold shadow-lg shadow-red-200 hover:bg-red-600 transition-all flex items-center gap-2"
          >
            <i className="fas fa-paper-plane"></i>
            一键发布
          </button>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-8 items-start justify-center">
        {/* Mobile Preview Screen */}
        <div className="flex-shrink-0 mx-auto lg:mx-0 sticky top-4">
          <div className="w-[375px] h-[812px] bg-white rounded-[40px] border-[12px] border-gray-900 shadow-2xl overflow-hidden relative flex flex-col">
            <div className="h-10 bg-white flex items-center justify-between px-6 text-xs font-bold text-gray-800 z-20"><span>9:41</span></div>
            <div className="flex-1 overflow-y-auto hide-scrollbar pb-16 bg-white">
              <div className="w-full bg-gray-50 relative group">
                <CoverComposer 
                  ref={coverRef}
                  imageUrl={image.url} 
                  title={coverText} 
                  selectedStyle={coverStyle} 
                  textWidth={textWidth} 
                  fontSize={fontSize}
                  aspectRatio={aspectRatio}
                />
                
                {showPublishToast && (
                  <div className="absolute inset-0 z-50 flex items-center justify-center animate-fade-in bg-black/20">
                    <div className="bg-black/75 backdrop-blur-md text-white px-8 py-5 rounded-3xl flex flex-col items-center gap-3 shadow-2xl">
                      <div className="w-12 h-12 bg-xhs-red rounded-full flex items-center justify-center text-2xl">
                        <i className="fas fa-check"></i>
                      </div>
                      <span className="font-black text-lg tracking-widest">已发布</span>
                    </div>
                  </div>
                )}
              </div>
              <div className="p-4 space-y-3">
                <h1 className="text-lg font-bold text-gray-800">{editableCopy.title}</h1>
                <p className="text-[15px] text-gray-800 leading-relaxed whitespace-pre-wrap">{editableCopy.content}</p>
                <div className="text-[15px] text-blue-600 font-medium">{editableCopy.tags.join(' ')}</div>
              </div>
            </div>
            <div className="h-14 bg-white border-t border-gray-100 absolute bottom-0 left-0 right-0 flex items-center px-4 justify-between z-30">
              <div className="flex-1 bg-gray-100 h-9 rounded-full px-4 flex items-center text-gray-400 text-sm mr-4">说点什么...</div>
              <div className="flex items-center gap-5 text-gray-700 text-xl"><i className="far fa-heart"></i><i className="far fa-star"></i></div>
            </div>
          </div>
        </div>

        {/* Editor Panel */}
        <div className="flex-1 w-full max-w-xl flex flex-col">
          <QualityCheckCard report={image.qualityReport} />

          <div className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden flex flex-col min-h-[500px]">
            <div className="flex border-b border-gray-100">
              <button onClick={() => setActiveTab('content')} className={`flex-1 py-4 font-bold text-sm uppercase transition-colors ${activeTab === 'content' ? 'text-xhs-red border-b-2 border-xhs-red' : 'text-gray-400'}`}>内容编辑</button>
              <button onClick={() => setActiveTab('cover')} className={`flex-1 py-4 font-bold text-sm uppercase transition-colors ${activeTab === 'cover' ? 'text-xhs-red border-b-2 border-xhs-red' : 'text-gray-400'}`}>封面设计</button>
            </div>
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {activeTab === 'content' ? (
                <>
                  <div>
                    <label className="text-xs font-bold text-gray-400 uppercase">笔记标题</label>
                    <input 
                      value={editableCopy.title} 
                      onChange={(e) => setEditableCopy({...editableCopy, title: e.target.value})} 
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl mt-1 font-bold focus:ring-2 focus:ring-xhs-red/20 outline-none"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 uppercase">正文内容</label>
                    <textarea 
                      value={editableCopy.content} 
                      onChange={(e) => setEditableCopy({...editableCopy, content: e.target.value})} 
                      rows={10} 
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl mt-1 text-sm resize-none focus:ring-2 focus:ring-xhs-red/20 outline-none"
                    />
                  </div>
                </>
              ) : (
                <>
                  <div>
                    <div className="flex justify-between items-center mb-1">
                      <label className="text-xs font-bold text-gray-400 uppercase">封面大字文案</label>
                      <button 
                        onClick={resetCoverTextWithAI}
                        disabled={isResettingText}
                        className="text-[10px] text-xhs-red font-bold hover:underline flex items-center gap-1 disabled:opacity-50"
                      >
                        <i className={`fas ${isResettingText ? 'fa-spinner fa-spin' : 'fa-sync-alt'}`}></i> 
                        {isResettingText ? '正在思考新文案...' : '重置并生成新文案'}
                      </button>
                    </div>
                    <input 
                      value={coverText} 
                      onChange={(e) => setCoverText(e.target.value)} 
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl font-bold focus:ring-2 focus:ring-xhs-red/20 outline-none"
                      placeholder="输入封面要展示的文字..."
                    />
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-xs font-bold text-gray-400 uppercase">尺寸比例</label>
                      <div className="flex gap-2 mt-2">
                        {['3:4', '1:1'].map(ratio => (
                          <button
                            key={ratio}
                            onClick={() => setAspectRatio(ratio as any)}
                            className={`flex-1 py-2 rounded-xl border-2 font-bold text-xs transition-all ${
                              aspectRatio === ratio ? 'border-xhs-red bg-red-50 text-xhs-red' : 'border-gray-100 text-gray-400'
                            }`}
                          >
                            {ratio}
                          </button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <label className="text-xs font-bold text-gray-400 uppercase">文字大小 ({fontSize}px)</label>
                      <input 
                        type="range" min="12" max="100" value={fontSize} 
                        onChange={(e) => setFontSize(Number(e.target.value))} 
                        className="w-full h-2 bg-gray-200 rounded-lg accent-xhs-red mt-4"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="text-xs font-bold text-gray-400 uppercase">文案样式</label>
                    <div className="grid grid-cols-3 gap-2 mt-2">
                      {TEXT_STYLES.map((style) => (
                        <button
                          key={style.id}
                          onClick={() => setCoverStyle(style)}
                          className={`px-2 py-3 rounded-xl border-2 text-[10px] font-bold transition-all ${
                            coverStyle.id === style.id 
                            ? 'border-xhs-red bg-red-50 text-xhs-red' 
                            : 'border-gray-100 bg-white text-gray-400'
                          }`}
                        >
                          {style.name}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="text-xs font-bold text-gray-400 uppercase">文案容纳宽度 ({textWidth}%)</label>
                    <input type="range" min="20" max="100" value={textWidth} onChange={(e) => setTextWidth(Number(e.target.value))} className="w-full h-2 bg-gray-200 rounded-lg accent-xhs-red mt-2"/>
                  </div>
                  <div className="pt-4 border-t border-gray-50">
                    <button onClick={onRegenerateImage} className="w-full py-3 bg-xhs-red text-white rounded-xl font-bold text-sm hover:bg-red-600 transition-colors shadow-lg shadow-red-100 flex items-center justify-center gap-2">
                      <i className="fas fa-magic"></i> 重新构思并渲染画面
                    </button>
                    <p className="text-[10px] text-gray-400 text-center mt-2">点击将根据产品特色重新生成具有设计感的场景图</p>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultPreview;